# Header
menu:
#  Home: /
#  Archives: /archives
  首页: /
  归档: /archives/
#  资源: /resource/
#  分类: /categories/
#  日志: /life/  #commend>hexo new page categories
rss: /atom.xml
sitemap: /sitemap.xml
banner: all-images/banner.jpg

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:


# Automatically Excerpt. Not recommend.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 64

# Local search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
